### PR TITLE
Generates shortcodes array

### PR DESCRIPTION
**Pull request by bensinclair**
This PR adds a script to Composer that allows us to generate a shortcodes array at will. Simply run `composer run update-resources`. 

It almost works but I am experiencing a few issues.

- [x] Composer is not downloading the iamcal/emoji-data GitHub repo. It's just hanging on my machine.
- [x] `var_export` method is removing single quotes from around numeric keys in the `src/shortcodes-array.php` file. This may not be a problem.
- [ ] I am not sure the best way to inject the `src/shortcodes-array.php` into the `LitEmoji` class. You can not set a constant in a class with a value that is a `require`.

I believe positioning and naming of files and folders might need to be changed also.

### CODE REVIEW

**Comment by bensinclair** [comment]
@joshmcrae We could always just pull the emoji data straight from the URL in GitHub if composer is going to be an issue. Maybe not best practice though...

**Comment by joshmcrae** [comment]
@bensinclair Compose was likely hanging due to the size of that repository (the README says it's around 4GB). I've switched to another emoji database.

The script has been updated so that existing keys with different formatting (dashes and underscores) are ignored in favour of what's already in our list. This ensures pulling the emoji database does not cause breakages for existing clients of our package.

I've removed `var_export` and replaced it with manual code generation.

The shortcodes array is imported once and accessed through a static method on the `LitEmoji` class.

**Comment by bensinclair** [comment]
@joshmcrae Awesome. I'm thinking we need a `get` method to pull in the array? We could then save the data to a property if we need to cache it better. Thoughts?

**Comment by joshmcrae** [comment]
@bensinclair Correct! Already implemented [here](https://github.com/elvanto/litemoji/pull/2/files#diff-b0bd5927e357627b749eb7d61d61eb28R158).

**Comment by bensinclair** [comment]
@joshmcrae Happy! I'll let you merge when ready

**Pull request merged**
